name: Documenter
on:
  push:
    paths:
      - 'docs/**'
      - '.github/workflows/Documenter.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required when authenticating with `GITHUB_TOKEN`, not needed when authenticating with SSH deploy keys
      pull-requests: read  # Required when using `push_preview=true`
      statuses: write  # Optional, used to report documentation build statuses
    steps:
      - uses: actions/checkout@v3
      - uses: julia-actions/setup-julia@latest
      - name: Install dependencies
        run: julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
      - name: Build
        env:
        run: julia --project=docs/ docs/make.jl
      - name: Create artifact
        run: |
          mkdir -p github-artifacts/docs
          # useless for now because GitHub pages doesn't work for private repositories
          mv docs/build ./github-artifacts/docs
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: docs
          path: ./github-artifacts

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          path: github-artifacts
      - name: Move docs
        run: mkdir -p github-deploy && mv github-artifacts/*/* github-deploy
      - name: Deploy on orphan branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./github-deploy
          publish_branch: docs
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          force_orphan: true
